# Generated by Django 4.0.3 on 2022-04-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('teams', '0002_remove_team_members_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(help_text='Select members for this team', to='users.user'),
        ),
    ]
