# Generated by Django 4.0.3 on 2022-04-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('teams', '0003_alter_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(help_text='Select members for this team', max_length=50, to='users.user'),
        ),
    ]
