# Generated by Django 4.0.3 on 2022-04-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETE', 'COMPLETE')], default='OPEN', max_length=15),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETE', 'COMPLETE')], default='OPEN', max_length=15),
        ),
    ]
